export const SQLITE_DATABASE_LIST = 'SQLITE_DATABASE_LIST';

export const MYSQL_DATABASE_LIST = 'MYSQL_DATABASE_LIST';

export const POSTGRESQL_DATABASE_LIST = 'POSTGRESQL_DATABASE_LIST';

export const DB_TYPE_MAP_STORE_KEY = {
  sqlite: SQLITE_DATABASE_LIST,
  mysql: MYSQL_DATABASE_LIST,
  postgresql: POSTGRESQL_DATABASE_LIST,
};
